name: Deploy Spring Boot Gradle Projects

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Build with Gradle
      run: ./gradlew build

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Deploy to AWS S3
      run: aws s3 cp build/libs/*.jar s3://patton/chms-service

    - name: Deploy to AWS Elastic Beanstalk
      run: |
        zip -r chms-service.zip .
        aws elasticbeanstalk create-application-version --application-name chms-service --version-label v1 --source-bundle S3Bucket=chms-service,S3Key=chms-service.zip
        aws elasticbeanstalk update-environment --environment-name YOUR_ENVIRONMENT_NAME --version-label v1